name: Odoo CI

on:
  push:
    branches: [ "s16.01" ]
  pull_request:
    branches: [ "s16.01" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # pip install -r requirements.txt
        # sudo apt-get install python3 python3-pip
        sudo apt-get install git python3-cffi build-essential wget python3-dev python3-venv python3-wheel libxslt-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less libpng-dev libjpeg-dev gdebi -y
        sudo -H pip3 install -r https://github.com/odoo/odoo/raw/16.0/requirements.txt

    - name: Run Tests
      run: |
        whoami

          
  deploy:
    runs-on: ubuntu-latest
    needs: build    
    name: deploy
    
    steps:

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DO_IP}}
        username: ${{ secrets.DO_USER }}
        password: ${{ secrets.DO_KEY }}
      
        script: |
        
          cd  /odoo/odoo-server/
          git fetch          
          git reset --hard origin/s16.01
              
          #git pull origin main
        